language: objective-c
osx_image: xcode12.2
xcode_workspace: TunnelKit.xcworkspace
xcode_scheme: TunnelKit-iOS
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro Max
cache:
  bundler: true
  cocoapods: true
branches:
  only:
    - master
install:
  - bundle install --jobs=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec pod repo update
  - travis_wait 40 bundle exec pod install
